steps:
  - checkout: self
    persistCredentials: true
  - template: ./build.yaml
  # - script: node common/scripts/install-run-rush.js version --bump --version-policy imodel-select --target-branch $(Build.SourceBranchName)
  #   displayName: rush version
  #   condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
  - script: node common/scripts/install-run-rush.js publish --apply --publish --include-all --target-branch $(Build.SourceBranchName) --add-commit-details --set-access-level public
    displayName: rush publish
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
    env:
      NPM_AUTH_TOKEN: $(npmToken)
