name: PR Tree-Widget Next performance benchmark

on:
  pull_request:
    branches:
      - tree-widget/next
    paths:
      - apps/performance-tests/**
      - packages/itwin/tree-widget/**
      - .github/workflows/benchmark-pr-tree-widget-next.yml
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  benchmark:
    uses: ./.github/workflows/benchmark-tree-widget-shared.yml
    with:
      display-name: 'Tree-Widget Next: Benchmark performance'
      benchmark-name: 'Tree-Widget Next benchmark'
      mode: 'push'
      gh-pages-branch: gh-pages-next
