name: Tree-Widget Next performance benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - tree-widget/next
    paths:
      - apps/performance-tests/**
      - packages/itwin/tree-widget/**

jobs:
  benchmark:
    uses: ./.github/workflows/benchmark-tree-widget-shared.yml
    with:
      display-name: 'Tree-Widget Next: Benchmark performance'
      benchmark-name: 'Tree-Widget Next benchmark'
      mode: 'push'
      gh-pages-branch: gh-pages-next
